/**
 * Turn the expanded scripts/content/type-details/*.json fields (typeOverview,
 * personalityAnalysis, abilityAnalysis, growthAdvice, careerPath) into the backfill
 * UPDATE statements in supabase/migrations/0005_expand_type_content.sql.
 *
 * Separate from generate-type-details-sql.ts (which targets 0004, already applied to
 * production) because 0004 documents a migration that already ran; this content revision
 * ships as its own migration instead of rewriting history. Matches by type_code, same as
 * 0002-0004.
 */
import fs from "node:fs";
import path from "node:path";

const DIR = path.join(__dirname, "content", "type-details");
const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();

type TypeDetail = {
  typeId: string;
  typeOverview: string;
  personalityAnalysis: string;
  abilityAnalysis: string;
  growthAdvice: string;
  careerPath: string;
};

let all: TypeDetail[] = [];
for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf-8")) as TypeDetail[];
  all = all.concat(data);
}

if (all.length !== 64) {
  throw new Error(`Expected 64 type-details entries, got ${all.length}`);
}
const ids = new Set(all.map((d) => d.typeId));
if (ids.size !== 64) {
  throw new Error("Duplicate typeId found in type-details JSON");
}
for (const d of all) {
  if (!d.typeOverview) throw new Error(`Missing typeOverview for ${d.typeId}`);
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

all.sort((a, b) => a.typeId.localeCompare(b.typeId));

const lines: string[] = [];
lines.push("-- Expands diagnosis_types content: replaces the short spec-sourced description");
lines.push("-- with a richer overview, and deepens personality/ability/growth/career text.");
lines.push("-- Generated by scripts/generate-type-overview-sql.ts from");
lines.push("-- scripts/content/type-details/*.json. Matches by type_code; no-op on a fresh");
lines.push("-- install where diagnosis_types is still empty at this point.");
for (const d of all) {
  lines.push(
    `update diagnosis_types set description = ${sqlStr(d.typeOverview)}, personality_analysis = ${sqlStr(
      d.personalityAnalysis
    )}, ability_analysis = ${sqlStr(d.abilityAnalysis)}, growth_advice = ${sqlStr(
      d.growthAdvice
    )}, career_path = ${sqlStr(d.careerPath)} where type_code = ${sqlStr(d.typeId)};`
  );
}
lines.push("");

const MIGRATION_PATH = path.join(
  __dirname,
  "..",
  "supabase",
  "migrations",
  "0005_expand_type_content.sql"
);
fs.writeFileSync(MIGRATION_PATH, lines.join("\n"));
console.log(`Wrote ${MIGRATION_PATH} (${lines.length} lines)`);
