/**
 * Turn scripts/content/type-details/*.json into the backfill UPDATE statements
 * appended to supabase/migrations/0004_add_type_details.sql.
 *
 * Matches rows by type_code (stable, human-readable) rather than the uuidv5 ids
 * used in generate-seed-sql.ts, mirroring the pattern already used in
 * 0002_add_character_images.sql / 0003_add_session_gender.sql.
 */
import fs from "node:fs";
import path from "node:path";

const DIR = path.join(__dirname, "content", "type-details");
const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();

type TypeDetail = {
  typeId: string;
  personalityAnalysis: string;
  abilityAnalysis: string;
  growthAdvice: string;
  careerPath: string;
  typeMoments: string[];
  compatibleTypeId: string;
  compatibleReason: string;
};

let all: TypeDetail[] = [];
for (const f of files) {
  const data = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf-8")) as TypeDetail[];
  all = all.concat(data);
}

if (all.length !== 64) {
  throw new Error(`Expected 64 type-details entries, got ${all.length}`);
}
const ids = new Set(all.map((d) => d.typeId));
if (ids.size !== 64) {
  throw new Error("Duplicate typeId found in type-details JSON");
}
for (const d of all) {
  const partner = all.find((p) => p.typeId === d.compatibleTypeId);
  if (!partner || partner.compatibleTypeId !== d.typeId) {
    throw new Error(`Asymmetric or missing compatible pair for ${d.typeId}`);
  }
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return "'{}'";
  const escaped = arr.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`);
  return `'{${escaped.join(",")}}'`;
}

all.sort((a, b) => a.typeId.localeCompare(b.typeId));

const lines: string[] = [];
lines.push("");
lines.push("-- Backfill: deep-dive content for all 64 types, generated by");
lines.push("-- scripts/generate-type-details-sql.ts from scripts/content/type-details/*.json.");
lines.push("-- Matches by type_code; no-op on a fresh install where diagnosis_types is still");
lines.push("-- empty at this point (seed.sql runs after migrations).");
for (const d of all) {
  lines.push(
    `update diagnosis_types set personality_analysis = ${sqlStr(
      d.personalityAnalysis
    )}, ability_analysis = ${sqlStr(d.abilityAnalysis)}, growth_advice = ${sqlStr(
      d.growthAdvice
    )}, career_path = ${sqlStr(d.careerPath)}, type_moments = ${sqlTextArray(
      d.typeMoments
    )}, compatible_type_id = (select id from diagnosis_types where type_code = ${sqlStr(
      d.compatibleTypeId
    )}), compatible_reason = ${sqlStr(d.compatibleReason)} where type_code = ${sqlStr(d.typeId)};`
  );
}
lines.push("");

const MIGRATION_PATH = path.join(__dirname, "..", "supabase", "migrations", "0004_add_type_details.sql");
const existing = fs.readFileSync(MIGRATION_PATH, "utf-8");
const marker = "-- Backfill:";
const head = existing.includes(marker) ? existing.slice(0, existing.indexOf(marker)).trimEnd() : existing.trimEnd();
fs.writeFileSync(MIGRATION_PATH, `${head}\n${lines.join("\n")}`);
console.log(`Wrote ${MIGRATION_PATH} (${lines.length} backfill lines + header)`);
