/**
 * Turn the parsed seed-data JSON (questions/types/master) into supabase/seed.sql.
 * Run after parse-questions.ts / parse-types.ts / parse-master.ts.
 *
 * IDs are deterministic (uuid v5 over a fixed namespace + natural code) so re-running
 * this generator produces the same SQL byte-for-byte given the same source data.
 */
import fs from "node:fs";
import path from "node:path";
import { v5 as uuidv5 } from "uuid";

const NAMESPACE = "3f7f6f2e-2b8f-4b8b-9a2a-restaurantdna"; // arbitrary fixed string, hashed by uuidv5 below
const NS = uuidv5(NAMESPACE, uuidv5.URL);

const idFor = (kind: string, code: string) => uuidv5(`${kind}:${code}`, NS);

const questions = JSON.parse(
  fs.readFileSync(path.join(__dirname, "seed-data", "questions.json"), "utf-8")
);
const types = JSON.parse(
  fs.readFileSync(path.join(__dirname, "seed-data", "types.json"), "utf-8")
);
const master = JSON.parse(
  fs.readFileSync(path.join(__dirname, "seed-data", "master.json"), "utf-8")
);

const VERSION_ID = idFor("version", "v2.0");

function sqlStr(s: string | null | undefined): string {
  if (s === null || s === undefined) return "null";
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return "'{}'";
  const escaped = arr.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`);
  return `'{${escaped.join(",")}}'`;
}

function sqlJsonb(obj: unknown): string {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];
lines.push("-- Auto-generated by scripts/generate-seed-sql.ts. Do not edit by hand.");
lines.push("-- Source: docs/spec/04-64-questions-scoring.md, 01-64-types.md, 02-job-format-role-master.md");
lines.push("");
lines.push("begin;");
lines.push("");

// diagnosis_versions
lines.push("-- Diagnosis version");
lines.push(
  `insert into diagnosis_versions (id, version_label, is_active) values (${sqlStr(
    VERSION_ID
  )}, 'v2.0', true);`
);
lines.push("");

// questions + choices + choice_scores
lines.push("-- Questions, choices, choice_scores (64 questions x 4 choices)");
for (const q of questions) {
  const questionId = idFor("question", q.questionId);
  lines.push(
    `insert into questions (id, version_id, question_code, scene_id, scene_title, visual_brief, display_order, question_text) values (${sqlStr(
      questionId
    )}, ${sqlStr(VERSION_ID)}, ${sqlStr(q.questionId)}, ${q.sceneId}, ${sqlStr(
      q.sceneTitle
    )}, ${sqlStr(q.visualBrief)}, ${q.displayOrder}, ${sqlStr(q.text)});`
  );
  for (const [i, c] of q.choices.entries()) {
    const choiceId = idFor("choice", `${q.questionId}-${c.code}`);
    lines.push(
      `insert into choices (id, question_id, choice_code, choice_text, display_order) values (${sqlStr(
        choiceId
      )}, ${sqlStr(questionId)}, ${sqlStr(c.code)}, ${sqlStr(c.text)}, ${i + 1});`
    );
    for (const s of c.scores) {
      lines.push(
        `insert into choice_scores (choice_id, axis_code, score_value) values (${sqlStr(
          choiceId
        )}, ${sqlStr(s.axis)}, ${s.value});`
      );
    }
  }
}
lines.push("");

// diagnosis_types
lines.push("-- Diagnosis types (64)");
for (const t of types) {
  const typeId = idFor("type", t.typeId);
  lines.push(
    `insert into diagnosis_types (id, type_code, name, catchcopy, description, family, primary_archetype, strengths, weaknesses, suited_jobs, suited_formats, suited_roles, tag_axis1, tag_axis2, tag_axis3, tag_axis4, tag_axis5, tag_axis6) values (${sqlStr(
      typeId
    )}, ${sqlStr(t.typeId)}, ${sqlStr(t.name)}, ${sqlStr(t.catchcopy)}, ${sqlStr(
      t.description
    )}, ${sqlStr(t.family)}, ${sqlStr(t.primaryArchetype)}, ${sqlTextArray(
      t.strengths
    )}, ${sqlTextArray(t.weaknesses)}, ${sqlTextArray(t.suitedJobs)}, ${sqlTextArray(
      t.suitedFormats
    )}, ${sqlTextArray(t.suitedRoles)}, ${sqlStr(t.tags.axis1)}, ${sqlStr(
      t.tags.axis2
    )}, ${sqlStr(t.tags.axis3)}, ${sqlStr(t.tags.axis4)}, ${sqlStr(t.tags.axis5)}, ${sqlStr(
      t.tags.axis6
    )});`
  );
}
lines.push("");

// job_format_role_master
lines.push("-- Job / format / role master vectors (95)");
for (const [i, m] of master.entries()) {
  lines.push(
    `insert into job_format_role_master (id, category, name, vector, display_order) values (${sqlStr(
      m.id
    )}, ${sqlStr(m.category)}, ${sqlStr(m.name)}, ${sqlJsonb(m.vector)}, ${i + 1});`
  );
}
lines.push("");
lines.push("commit;");
lines.push("");

const OUT = path.join(__dirname, "..", "supabase", "seed.sql");
fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT} (${lines.length} lines)`);
